# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Î» Lovelace
email: 
description: > # this means to ignore newlines until "baseurl:"
  A collaborative recommender system for tweets; a personalised tweet stream. 
  Module: COMP47250, a 30 ECTS group project, summer 2016 at University 
  College Dublin.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://jonrh.github.io/lambda-lovelace/" # the base hostname & protocol for your site
twitter_username: jonrh
github_username:  jonrh

# Build settings
markdown: kramdown
